# Generated by Django 2.2.2 on 2020-07-14 09:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_auto_20200705_2052'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'Cities',
            },
        ),
        migrations.CreateModel(
            name='MemberPaymentHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'MemberPaymentHistory',
                'verbose_name_plural': 'MemberPaymentHistorys',
            },
        ),
        migrations.CreateModel(
            name='MembershipDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('second_name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.IntegerField()),
                ('date_joined', models.DateField()),
                ('date_terminated', models.DateField()),
                ('is_paid_up', models.BooleanField()),
                ('notes', models.TextField()),
                ('city_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.City')),
            ],
            options={
                'verbose_name': 'MembershipDetail',
                'verbose_name_plural': 'MembershipDetails',
            },
        ),
        migrations.CreateModel(
            name='MembershipType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=50)),
                ('monthly_price', models.IntegerField()),
                ('yearly_price_after_discount', models.IntegerField()),
            ],
            options={
                'verbose_name': 'MembershipType',
                'verbose_name_plural': 'MembershipTypes',
            },
        ),
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.AddField(
            model_name='membershipdetail',
            name='membership_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.MembershipType'),
        ),
    ]
