# Generated by Django 2.2.2 on 2020-07-14 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_title_userpreferences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershipdetail',
            name='title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Title'),
        ),
    ]
