# Generated by Django 2.2.2 on 2020-07-20 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200714_1723'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memberpaymenthistory',
            name='user',
        ),
        migrations.RemoveField(
            model_name='membershipdetail',
            name='city_id',
        ),
        migrations.RemoveField(
            model_name='membershipdetail',
            name='membership_type',
        ),
        migrations.RemoveField(
            model_name='membershipdetail',
            name='title',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='MemberPaymentHistory',
        ),
        migrations.DeleteModel(
            name='MembershipDetail',
        ),
        migrations.DeleteModel(
            name='MembershipType',
        ),
    ]
