# Generated by Django 2.2.2 on 2020-07-20 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200720_0813'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Title',
        ),
    ]
