# Generated by Django 2.2.2 on 2020-07-20 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_delete_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='saved_user_prefereces',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
