# Generated by Django 2.2.2 on 2020-07-23 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_userpreferences_saved_user_prefereces'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreferences',
            name='option_1',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='option_2',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='option_3',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='saved_user_prefereces',
            field=models.BooleanField(default=False),
        ),
    ]
