# Generated by Django 2.2.2 on 2020-07-27 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membershipdetail',
            old_name='second_name',
            new_name='last_name',
        ),
        migrations.RemoveField(
            model_name='membershipdetail',
            name='surname',
        ),
    ]
