# Generated by Django 2.2.2 on 2020-07-27 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0005_auto_20200727_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipdetail',
            name='membership_term',
            field=models.CharField(choices=[('Monthly', 'M'), ('Yearly', 'Y')], default='M', max_length=50),
            preserve_default=False,
        ),
    ]
