# Generated by Django 2.2.2 on 2020-07-27 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0007_auto_20200727_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershipdetail',
            name='date_joined',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='membershipdetail',
            name='date_terminated',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='membershipdetail',
            name='is_paid_up',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='membershipdetail',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='membershipdetail',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='membershipdetail',
            name='telephone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
