# Generated by Django 2.2.2 on 2020-07-27 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0008_auto_20200727_1130'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_mode', models.CharField(choices=[('M', 'Monthly'), ('O', 'One Time')], max_length=50)),
                ('amount', models.FloatField()),
            ],
        ),
    ]
