# Generated by Django 2.2.2 on 2020-07-27 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0009_donation'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershiptype',
            name='membership_group',
            field=models.CharField(default='gold_group', max_length=50),
            preserve_default=False,
        ),
    ]
